version: '3'

services:
  bellywelly:
    image: bellywellycapston/bellywelly
    container_name: bellywelly-server
    hostname: bellywelly-server
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"
    depends_on:
      - bellywelly